<!DOCTYPE html>
*This tells the web browser to start interpreting the following as html 
<head>
*The head contains information such as metadata
<title> </title>
*The text between the title tags will appear when the website is opened in tabs
<link href=”insertyourcsslinkhere” rel=”stylesheet” type=”text/css” href=”style.css”>
*The line above links your html to the css
</head>
<body>
*The contents of your website go here
</body>
</html>
